import React from 'react';
import Link from 'next/link';
import { CheckCircle2, HeartHandshake, Mail, ShieldCheck, Users } from 'lucide-react';

export const metadata = { title: 'Fes-te soci o col·laborador | Associació Cristiana EducaFe', description: 'Coneix les formes de vincular-te de manera estable amb l’Associació Cristiana EducaFe.' };

export default function FesTeSociPage() {
  return (
    <div className="space-y-16 py-12">
      <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl space-y-4"><div className="inline-flex items-center gap-2 rounded-full border border-sky-200 bg-sky-50 px-3.5 py-1.5 text-xs font-bold uppercase tracking-wider text-sky-800"><Users className="h-4 w-4" /> Comunitat EducaFe</div><h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-slate-900">Fes-te soci o col·laborador</h1><p className="text-base sm:text-lg leading-relaxed text-slate-600">EducaFe creix amb persones que comparteixen la seva vocació educativa, el compromís amb les famílies i el desig de servir la comunitat de manera responsable.</p></div></section>
      <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <article className="rounded-3xl border border-sky-200 bg-white p-8 shadow-sm"><ShieldCheck className="h-8 w-8 text-sky-700" /><h2 className="mt-5 text-2xl font-bold text-slate-900">Persona sòcia</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">Forma part de la vida associativa i participa d’acord amb els Estatuts, els acords de l’Assemblea i els procediments interns d’admissió.</p><ul className="mt-5 space-y-3 text-sm text-slate-700">{['Conèixer i donar suport als fins de l’associació', 'Participar en la vida associativa segons els Estatuts', 'Assumir els compromisos aprovats per l’entitat'].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-sky-600" />{item}</li>)}</ul></article>
        <article className="rounded-3xl border border-teal-200 bg-white p-8 shadow-sm"><HeartHandshake className="h-8 w-8 text-teal-700" /><h2 className="mt-5 text-2xl font-bold text-slate-900">Persona col·laboradora</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">Dona suport de manera periòdica o puntual sense adquirir la condició de soci: amb una aportació, materials, coneixements professionals o ajuda en activitats concretes.</p><ul className="mt-5 space-y-3 text-sm text-slate-700">{['Col·laboració flexible', 'Informació clara sobre la destinació del suport', 'Sense compromís de participar en el govern de l’entitat'].map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-teal-600" />{item}</li>)}</ul></article>
      </div></section>
      <section className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-3xl bg-slate-900 p-8 sm:p-10 text-white"><h2 className="text-2xl font-bold">Demana informació abans de decidir</h2><p className="mt-3 max-w-2xl text-sm leading-relaxed text-slate-300">T’enviarem la informació vigent sobre incorporació, drets, deures i formes de col·laboració. Enviar una consulta no et converteix automàticament en soci ni genera cap obligació econòmica.</p><div className="mt-6 flex flex-wrap gap-3"><a href="mailto:info@asociacioneducafe.org?subject=Informació%20per%20fer-me%20soci%20o%20col·laborador" className="inline-flex items-center gap-2 rounded-xl bg-sky-500 px-5 py-3 text-sm font-bold text-white hover:bg-sky-600"><Mail className="h-4 w-4" /> Demanar informació</a><Link href="/transparencia" className="rounded-xl border border-slate-700 px-5 py-3 text-sm font-bold text-slate-200 hover:bg-slate-800">Consultar transparència</Link></div></div></section>
    </div>
  );
}
