import React from 'react';
import Link from 'next/link';
import { CheckCircle2, FileText, Mail, Scale, ShieldCheck } from 'lucide-react';

export const metadata = { title: 'Transparència | Associació Cristiana EducaFe', description: 'Informació institucional, registral i de bon govern de l’Associació Cristiana EducaFe.' };
const documents = ['Estatuts inscrits', 'Resolució d’inscripció registral', 'Targeta d’identificació fiscal', 'Informació econòmica del darrer exercici tancat', 'Pla de voluntariat i documents d’entorn segur'];

export default function TransparenciaPage() {
  return (
    <div className="space-y-16 py-12">
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="max-w-3xl space-y-4"><div className="inline-flex items-center gap-2 rounded-full border border-sky-200 bg-sky-50 px-3.5 py-1.5 text-xs font-bold uppercase tracking-wider text-sky-700"><Scale className="h-4 w-4" /> Rendició de comptes</div><h1 className="text-3xl sm:text-5xl font-extrabold tracking-tight text-slate-900">Transparència institucional</h1><p className="text-base sm:text-lg leading-relaxed text-slate-600">Compartim de manera clara la identitat jurídica, la governança i els compromisos de l’Associació Cristiana EducaFe.</p></div></section>
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid grid-cols-1 md:grid-cols-3 gap-5"><div className="rounded-2xl border border-slate-200 bg-white p-6"><ShieldCheck className="h-6 w-6 text-sky-700" /><div className="mt-4 text-xs font-bold uppercase text-slate-500">Entitat</div><div className="mt-1 font-bold text-slate-900">Associació Cristiana EducaFe</div></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><FileText className="h-6 w-6 text-teal-700" /><div className="mt-4 text-xs font-bold uppercase text-slate-500">NIF</div><div className="mt-1 font-mono font-bold text-slate-900">G19357789</div></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><Scale className="h-6 w-6 text-amber-700" /><div className="mt-4 text-xs font-bold uppercase text-slate-500">Registre</div><div className="mt-1 font-bold text-slate-900">Generalitat de Catalunya núm. 75881</div></div></div></section>
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-3xl border border-slate-200 bg-slate-50 p-8 sm:p-10"><h2 className="text-2xl font-bold text-slate-900">Documentació institucional</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-slate-600">L’entitat està revisant i ordenant el repositori públic per garantir que cada descàrrega correspongui al document complet i vigent. Mentre finalitza aquest procés, la documentació es pot sol·licitar directament.</p><ul className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-3">{documents.map((item) => <li key={item} className="flex gap-2 rounded-xl border border-slate-200 bg-white p-4 text-sm text-slate-700"><CheckCircle2 className="h-4 w-4 shrink-0 text-teal-600" />{item}</li>)}</ul><a href="mailto:info@asociacioneducafe.org?subject=Sol·licitud%20de%20documentació%20institucional" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-sky-600 px-5 py-3 text-sm font-bold text-white hover:bg-sky-700"><Mail className="h-4 w-4" /> Sol·licitar documentació</a></div></section>
      <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-3xl bg-slate-900 p-8 text-white"><h2 className="text-xl font-bold">Governança i participació</h2><p className="mt-3 text-sm leading-relaxed text-slate-300">La informació sobre la Junta Directiva, la missió i la naturalesa de l’acció social està disponible a la secció Qui Som.</p><Link href="/qui-som#junta" className="mt-5 inline-block text-sm font-bold text-sky-300 underline">Veure Qui Som i Junta Directiva</Link></div></section>
    </div>
  );
}
